### ISSUE TITLE
Error: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by 4lador** [vadimdemedes/google-images#17]
If the query contains characters used by google search like '-', the module throw a TypeError

```
TypeError: Cannot read property 'map' of undefined
    at Client._buildResponse (E:\Dev\MisterGoodNews\AuthorBot\mgn-authorbot\node_modules\google-images\index.js:60:23)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Maybe we could delete this character from the string in the `search` function ?

I'll create a pull request with the workaround :)

**Comment by 4lador** [comment]
I found the same issue with the space characters
